### ISSUE TITLE
Cuda error when running nvidia-docker with CUDA 8 

### ISSUE THREAD

**Issue by saurabhvyas** [IndicoDataSolutions/finetune#103]
I am trying to run training with Nvidia-docker , I have cuda 8 and 

getting the following error, when running training file , 

Here is the image of my terminal output : https://ibb.co/eRoj5p

Here is the image of nvidia-smi and nvidia-docker on terminal :  https://ibb.co/jEtOy9

I am not able to figure out what the problem is I have docker and compatible verison of nvidia-docker, I have nvidia gpus and cuda 8, I have verified performing nvidia-smi test on nvidia-docker, but when I run the finetune docker image and then run training file , it gives the error mentioned in screenshot.

I would really appreicate if someone can point me towards a right direction to solve this.

**Comment by saurabhvyas** [comment]
It is my bad, my driver version is missing the minimum requirement by point decimal value , Ill have to update my driver.

**Comment by madisonmay** [comment]
No worries! Glad you were able to figure thing out.
