### ISSUE TITLE
Regressor predict output is None

### ISSUE THREAD

**Issue by chiayewken** [IndicoDataSolutions/finetune#115]
**Describe the bug**
After fitting the Regressor model, calling predict returns None instead of list or array of predictions.

**Minimum Reproducible Example**
import numpy as np
from finetune import Regressor

x_test = np.array(['the quick fox jumped over the lazy brown dog'] * 100)
y_test = np.random.random(100)
model_test = Regressor(n_epochs=1, val_interval=100/2/3)
model_test.fit(x_test, y_test)
model_test.predict(x_test)  # Returns None

**Additional context**
Finetune was installed from source, 0.3.1 master branch. Environment is google colab python3 (gpu).

**Comment by madisonmay** [comment]
Thanks for the helpful bug report -- I'm surprised this wasn't caught by tests.  Looking into this now.

--Madison

**Comment by madisonmay** [comment]
Hotfixed by #117.  Thanks again for the bug report @chiayewken!  Somehow our `Regressor` test got removed in a past rebase. I've added a Regressor regression test to make sure this continues to work :)
