### ISSUE TITLE
Kernel dying when running the SST classification example.

### ISSUE THREAD

**Issue by helboukkouri** [IndicoDataSolutions/finetune#123]
Hi! I'm trying to run the [SST classification example](https://github.com/IndicoDataSolutions/finetune/blob/development/finetune/datasets/stanford_sentiment_treebank.py) in a Jupyter notebook, but the kernel keeps dying as soon as the TensorFlow variables are initialized.

I guess that maybe the model is too big to fit in memory. But I tried to lower the batch size to 1 and the max_length to 10, and the kernel still died anyway.

I tried this on a machine with 16 Gb of RAM and 8 CPUs, as well as on the same machine but using 2 GeForce GTX 970 with each 4 Gb of memory.

Do I need more memory to be able to use the classification model ?

**Comment by helboukkouri** [comment]
Thanks for your answer :)

I tried running the classifier on another machine with more RAM and got it to work ! So I think the issue was that the GPUs didn't have enough memory (the model has to require > 2 x 4 Gb) and since the machine is shared with other users, it probably didn't have enough memory left to run in CPU mode.

Anyway, thanks again for your answer. I'm closing this issue :)

**Comment by madisonmay** [comment]
@helboukkouri glad you were able to get things working!  The model should be runnable on a 4GB GPU (I've run it on a single GTX 980) so I do still think it's a bit odd you received a kernel error, but it's possible that something else was taking up GPU memory at the time.  You could also try `low_memory_mode=True` which should help quite a bit with train time memory usage.

**Comment by helboukkouri** [comment]
Weird it didn't work on my GPUs then. Nobody was using them at the time, and I even tried using `low_memory_mode=True` but it didn't help.

I'll keep you informed if I ever get the finetuning to work on GPU. Thanks @madisonmay :)
