### ISSUE TITLE
Wrong indices in oversampling code?

### ISSUE THREAD

**Issue by phiresky** [IndicoDataSolutions/finetune#186]
**Describe the bug**

In these lines:

https://github.com/IndicoDataSolutions/finetune/blob/9a62687d964a6ac79e95587aad3a8de824969bb4/finetune/classifier.py#L13-L16

It seems to me that the return statement should either be

`return [Xs[i[0]] for i in idxs], [Y[i[0]] for i in idxs]`

(Y instead of Ys)

or

`return [Xs[i[0]] for i in idxs], Ys`

Since as is you're basically applying the originalIndex->sampledIndex mapping twice

I'm not sure if this actually causes wrong labels but it looks like it could.

**Comment by madisonmay** [comment]
Hi @phiresky,

You're correct... this must have also died in the most recent refactor. Thanks for your solution --both of your implementations are correct but the second seems cleaner. I can put in a fix for this tonight along with a test, but if you'd like to contribute a patch yourself I will gladly accept it.
