### ISSUE TITLE
model loading error

### ISSUE THREAD

**Issue by erdenebayrd** [IndicoDataSolutions/finetune#205]
Describe the bug
After saving a model on 0.4.1 using Classifier.save("my_model.model"), upgrading to 0.5.12,
Loading using Classifier.load("my_model.model") results in KeyError: 'base_model_path'

**Comment by madisonmay** [comment]
Hi @erdenebayrd,

Thanks for the bug report. We're currently tracking this as part of #185.

We are aware of the problem but the resolution is a bit non trivial and we've decided to mark this as a "won't fix".  We do not intend to break backwards compatibility of model files moving forward.

Apologies for the trouble.  If the model was trained on a relatively small dataset re-training is probably the best course of action -- you may see performance gains from the modifications made as part of the 0.5 release anyhow.

--Madison
