### ISSUE TITLE
difference

### ISSUE THREAD

**Issue by erdenebayrd** [IndicoDataSolutions/finetune#210]
what is the difference between Classifier.load("my_model") and Classifier().load("my_model") ?

**Comment by benleetownsend** [comment]
`Classifier.load("my_model")` would be considered the correct way to do this. `Classifier()` will instantiate one object, then `.load` will instantiate another from the file. Whereas `Classifier.load("my_model")` bypasses this first object. In reality, both are fine as the initial object will quickly get cleaned up. 

Hope this helps.
