### ISSUE TITLE
Model load fails if tensorboard directory is inaccessible

### ISSUE THREAD

**Issue by phiresky** [IndicoDataSolutions/finetune#218]
I can't load a model on a different computer, because the home directory is different, which causes this:

https://github.com/IndicoDataSolutions/finetune/blob/8d0ecc2dc8d6d38ac68e31cfb4a5ec445a2da111/finetune/base.py#L84-L89

to fail with Permission denied.

I worked around it with this script:

```python
import joblib
import sys
p = sys.argv[1]
a, b = joblib.load(p)

b.config.tensorboard_folder = None

joblib.dump((a,b), p+".export")
```

but I feel like this case should be handled by the library.

**Comment by benleetownsend** [comment]
fixed in #221
