### ISSUE TITLE
Transference between finetune models

### ISSUE THREAD

**Issue by Guillermogsjc** [IndicoDataSolutions/finetune#256]
It would be nice to be able to transfer between a fitted model and another one, for example:

```python
from finetune import Classifier

classifier = Classifier()
classifier.finetune(X, y)

# and later build a model with all layers but the last one the same:
classifier.transfer_finetune(X, y_with_different labels)
```
Meaning this a drop of the last layer only. Is there any way to cut this at high level on the API?

The use case:  you have **tags** on text and now want to use this featurization to get down to **intents**.

**Comment by madisonmay** [comment]
We actually do support this! Give the following a shot:
```
from finetune import Classifier

tags_classifier = Classifier()
tags_classifier.fit(X, Y)
tags_classifier.create_base_model('tags_base_model.jl')
# saves all weights from the tags classifier as a new "base model"

intent_classifier = Classifier(base_model=path='tags_base_model.jl')
# loads base model weights from tags classifier
intent_classifier.fit(intentX, intentY)
...
```

**Comment by Guillermogsjc** [comment]
Oh, great thanks!

**Comment by madisonmay** [comment]
Let me know if you have trouble getting things to work, but closing this issue for now!

Happy hacking :)
