### ISSUE TITLE
Avoid estimator rebuilding for fast inference

### ISSUE THREAD

**Issue by Guillermogsjc** [IndicoDataSolutions/finetune#259]
Based on a contribution by @dimidd and updated for `>=0.6` versions , I propose the inclusion of this `_inference2` and `fast_predict` method. `_cached_inference` explodes on time use after every repetition (it has * 2 execution time after every prediction), while `fast_predict` on this [gist](https://gist.github.com/Guillermogsjc/1ebb9ef8e946c9362ae02ef733a32e75) does not.

**Comment by madisonmay** [comment]
Hi @Guillermogsjc,

Another awesome find!  Going to take a look at your gist and see if we can't get this in quickly (as part of a 0.6.2 push).

**Comment by madisonmay** [comment]
Found the issue -- failure to reset an iterator that keeps track of some padding for batching in the _data_generator.  See: https://github.com/IndicoDataSolutions/finetune/pull/260

**Comment by Guillermogsjc** [comment]
in `0.6.2` everything is fine with `_cached_inference`, thanks for the update

**Comment by madisonmay** [comment]
Thanks for verifying and thanks for the bug report!
