### ISSUE TITLE
Exception when calling .predict on default Comparison model

### ISSUE THREAD

**Issue by pmiller10** [IndicoDataSolutions/finetune#279]
**Describe the bug**
There's an exception when calling the Comparison().predict function. It only happens when the model has not been trained. If the model is trained on a single row, or a trained model is loaded from disk, it executes as expected. This happens when calling `predict` or `predict_proba`. I reproduced it on tags 0.6.3 and 0.6.2 on both GPU and CPU.

The exception:
```
>>> p = m.predict_proba([('Information Security Threat Hunter Lead', 'Business Analyst')])
/Users/tnguyen/anaconda3/envs/olympus/lib/python3.6/site-packages/finetune/config.py:80: UserWarning: Failed to find available GPUS.  Falling back to CPU only mode.
  warnings.warn("Failed to find available GPUS.  Falling back to CPU only mode.")
Inference:   0%|                                                                                                                                          | 0/1 [00:00<?, ?it/s]Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/tnguyen/anaconda3/envs/olympus/lib/python3.6/site-packages/finetune/target_models/comparison.py", line 72, in predict_proba
    return BaseModel.predict_proba(self, pairs)
  File "/Users/tnguyen/anaconda3/envs/olympus/lib/python3.6/site-packages/finetune/base.py", line 399, in predict_proba
    raw_probas = self._predict_proba(*args, **kwargs)
  File "/Users/tnguyen/anaconda3/envs/olympus/lib/python3.6/site-packages/finetune/base.py", line 392, in _predict_proba
    raw_preds = self._inference(Xs, PredictMode.PROBAS)
  File "/Users/tnguyen/anaconda3/envs/olympus/lib/python3.6/site-packages/finetune/base.py", line 375, in _inference
    return [pred[mode] if mode else pred for pred in predictions]
  File "/Users/tnguyen/anaconda3/envs/olympus/lib/python3.6/site-packages/finetune/base.py", line 375, in <listcomp>
    return [pred[mode] if mode else pred for pred in predictions]
  File "/Users/tnguyen/anaconda3/envs/olympus/lib/python3.6/site-packages/tqdm/_tqdm.py", line 1022, in __iter__
    for obj in iterable:
  File "/Users/tnguyen/anaconda3/envs/olympus/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 617, in predict
    estimator_spec.predictions, predict_keys)
  File "/Users/tnguyen/anaconda3/envs/olympus/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1018, in _extract_keys
    'provided %s.' % (existing_keys, predict_keys))
ValueError: Expected to run at least one output from dict_keys(['FEAT', 'ATTENTION']), provided PROBA.
```

**Minimum Reproducible Example**
```
from finetune import Comparison
m = Comparison()
p = m.predict_proba([('Goodbye cruel world', 'Hello world!')])
```

**Expected behavior**
When calling `predict` a 0 or 1. When calling `predict_proba` a probability distribution.

**Comment by madisonmay** [comment]
Thanks for the issue @pmiller10, will take a peek!  

--Madison

**Comment by madisonmay** [comment]
At first glance the "solution" to this problem might be a better error message that says something along the lines of "Cannot predict on an untrained model."  What behavior were you expecting here @pmiller10? A "prediction" on top of the randomly initialized weights that you could use as a baseline?

**Comment by pmiller10** [comment]
I thought the weights would be initialized to pre-trained weights. Are they randomly initialized?

**Comment by madisonmay** [comment]
The weights of the base model are initialized to the pre-trained weights, however, for any given task a small portion of the weights (the target model) is randomly initialized. In other words, there is no pre-trained `Comparison` model, just a pre-trained `LanguageModel` that can be finetuned by appending a small randomly initialized dense layer on top and finetuning all the weights of the composite model.

**Comment by madisonmay** [comment]
If you do want to do comparison to just look at the pre-trained feature similarity, you could use the featurize method we expose.  

Example code below:

```
from finetune import Classifier
from scipy.spatial.distance import cosine
model = Classifier()
features = model.featurize(['cat', 'dog']
similarity = 1 - cosine(features[0], features[1])
print("Similarity: {}".format(similarity))
```                                                                                                

Which produces:
```
Similarity: 0.902673602104187
```

**Comment by pmiller10** [comment]
My goal was just to get a baseline before finetuning on our dataset, so that `featurize` method would be what I'm looking for. Thanks!

**Comment by madisonmay** [comment]
Glad we could be helpful!  Good luck with your work :)
