### ISSUE TITLE
implementation of ExponentialMovingAverage is not correct

### ISSUE THREAD

**Issue by FrankWork** [IndicoDataSolutions/finetune#29]
```
def get_ema_if_exists(v, gvs):
    name = v.name.split(':')[0]
    ema_name = name+'/ExponentialMovingAverage:0'
    ema_v = [v for v in gvs if v.name == ema_name]
    if len(ema_v) == 0:
        ema_v = [v]
    return ema_v[0]

def get_ema_vars(*vs):
    if tf.get_variable_scope().reuse:
        gvs = tf.global_variables()
        vs = [get_ema_if_exists(v, gvs) for v in vs]
    if len(vs) == 1:
        return vs[0]
    else:
        return vs
```

`g, b = get_ema_vars(g, b)` I think `g, b` is the original tensor, not the ema

**Comment by madisonmay** [comment]
@FrankWork seems like the primary issue is that ExponentialMovingAverage variables are never set.  I'm assuming this is just dead code at this point and can be removed.  I've put up a PR for a fix but am checking with the original project author (Alec Radford) before merge to make sure -- I want to ensure that the EMA variables were not also not available at train time.

**Comment by madisonmay** [comment]
Confirmed with Alec that was the case.  Thanks again for the report @FrankWork!
