### ISSUE TITLE
Support older TensorFlow versions (<= 1.12)

### ISSUE THREAD

**Issue by dimidd** [IndicoDataSolutions/finetune#295]
**Describe the bug**
The Readme states that `tensorflow-gpu >= 1.6` is required, however looks like the current version requires TF >= 1.13, since there were some API changes such as [`device_util`](https://github.com/IndicoDataSolutions/finetune/blob/b7819e3a066d0b400c76da04eeba1f8e42cdb0d6/finetune/util/estimator.py#L2). Moreover, TF 1.13 is based on cuda 10, which further complicates upgrades. Would you be interested in a PR to restore backward compatability?

**Minimum Reproducible Example**
`from tensorflow.python.distribute import device_util`

**Expected behavior**
A correct import

**Additional context**
https://stackoverflow.com/questions/56026137/device-util-not-found-in-tensorflow

**Comment by madisonmay** [comment]
Absolutely!  Yeah at the very least we need to update the README there -- and I agree that adding compatibility for versions of tensorflow compatible with CUDA 9.0 would be nice.  We've been a little fast and loose with breaking backwards compatibility there as the community for finetune isn't huge at the moment, so apologies for any trouble that may have caused you folks.

I think most of the necessary changes for this would be isolated to:
https://github.com/IndicoDataSolutions/finetune/blob/development/finetune/util/estimator.py

**Comment by madisonmay** [comment]
After some thought we intend to support 1.14+ and (eventually) 2.x only moving forward.  The portions of the tensorflow API we use in finetune have been rather unstable and we've opted for ease of maintenance over broad tensorflow version support so far.  Apologies for any trouble this might have caused you.  

If you are willing we would absolutely still welcome a backwards compatibility PR, but we don't realistically have the developer resources to take on that task right now.
