### ISSUE TITLE
Whole Word Masking Models

### ISSUE THREAD

**Issue by khoa-ho** [IndicoDataSolutions/finetune#302]
https://github.com/google-research/bert just added whole word masking modes. It would be great if finetune supports those as well.

**Comment by benleetownsend** [comment]
Thanks for the suggestion, I will try to do this today or tomorrow.

**Comment by madisonmay** [comment]
Hi @khoa-ho,

The new BERT whole word masking model was just added here: #303

**Comment by khoa-ho** [comment]
@benleetownsend @madisonmay That's great. Thank you guys!
