### ISSUE TITLE
model loading syntax 

### ISSUE THREAD

**Issue by jinli-ece-cs** [IndicoDataSolutions/finetune#306]
**Describe the bug**
If we load the model by 
```
m = Classifier() 
m.load('model_path')
m.predict_proba(...) 
```
then we end up with the error 
_ValueError: Expected to run at least one output from dict_keys(['PERPLEXITY', 'ATTENTION', 'GEN_TEXT', 'FEAT']), provided ['PROBA']._ 

If we load the model by 
```
m = Classifier().load('model_path')
m.predict_proba(...)
```
then it works fine.

**Additional context**
Just thought I'd post it since it took me a while to figure out.

**Comment by madisonmay** [comment]
Hi @jinli-ece-cs!

Thanks for the bug report, someone else reported the same thing to me in person recently.  We can definitely add an exception if someone attempts to use this as an instance method rather than a classmethod.

**Comment by madisonmay** [comment]
Hi @jinli-ece-cs -- this behavior should now raise an exception thanks to #309.  Thanks again for the bug report!
