### ISSUE TITLE
GPT-2 model params

### ISSUE THREAD

**Issue by bakszero** [IndicoDataSolutions/finetune#317]
What is the current GPT-2 paramater size being used? 

Is it the 117M model or the 345M -- if only the prior, can the latter be added as well? This is indeed amazing work, would love to see this scale to a lot of different architectures in the near future.

**Comment by benleetownsend** [comment]
Currently only 117M is included. I will add this in when I get a chance, it shouldn't take too long. 
Thanks for the kind words. We love to see people making good use of finetune.

**Comment by benleetownsend** [comment]
This is now supported in the development branch as of #319. Available on development under the name `finetune.base_models.GPT2ModelMedium`
