### ISSUE TITLE
Use BERT multilingual as base model in BERT

### ISSUE THREAD

**Issue by Guillermogsjc** [IndicoDataSolutions/finetune#326]
If the base model used for finetune is multiligual one (https://github.com/google-research/bert/blob/master/multilingual.md) it would be great, as any translation at NLU time would be not needed.

Regards.

**Comment by madisonmay** [comment]
Hi @Guillermogsjc!

We do actually support the BERT multilingual model, just not by default.  To use BERT multilingual as your base, you can do the following:

```
from finetune.base_models import BERTModelMultilingualCased

model = Classifier(base_model=BERTModelMultilingualCased)
```

Hope this helps! Will update our online documentation to make sure this is covered here shortly.

**Comment by Guillermogsjc** [comment]
Thank you  very much Madison
