### ISSUE TITLE
Cannot use the whole text to train Classifier model

### ISSUE THREAD

**Issue by yangliu2** [IndicoDataSolutions/finetune#329]
I'm trying to train a multiclass model using Classifier class. Some text is longer than 512 bytes and the default option is to trim it. Not sure how that translate to # of char, 4K per char? I tried to increase it, but it won't fit GPU memory after 1024. And the model accuracy (average F1) went down. 
`config.Settings.max_length = 1024`
`config.Settings.interpolate_pos_embed = True`

I also tried `config.Settings.chunk_long_sequences = True` but it generated multiple examples, and give multiple prediction, so I don't think that's the right option. 

When I used Finetune last year, it used to take long texts without trimming. Is there anyway I can use that. Longer training time is fine.

**Comment by madisonmay** [comment]
Hi @yangliu2,

We currently only support using `chunk_long_sequences` for the `SequenceLabeler` class but we are tracking that this is a desired feature. 

Later this week @matthewbayer intends to put in some hours adding support for using other model types with the `chunk_long_sequences` option.  If you're willing to wait until early next week that support for that should be in.  I'd like to expose support for aggregating chunks via either mean or max pool before feeding into the final classifier.

If this is a pressing need, my best recommendation is to split on paragraphs or similar and do postprocessing on your own.

**Comment by yangliu2** [comment]
Thank you for the quick reply! I would probably do the same thing you are doing. I will just wait until it comes out. I may do preprocessing since I believe the later part of the text is more important.

**Comment by madisonmay** [comment]
Sounds great, glad we can be helpful!

**Comment by madisonmay** [comment]
Hi @yangliu2 -- sorry we never follow up on this!  The `chunk_long_sequences` option is now available for `Classifier` models as of the 0.8 release.  Let us know if you have any further issues.

**Comment by yangliu2** [comment]
Thank you kindly for the reply! I sort of got around it with your suggestions, but I will definitely try your implementation.
