### ISSUE TITLE
TypeError: _initialize_local() got an unexpected keyword argument 'cluster_resolver'

### ISSUE THREAD

**Issue by emtropyml** [IndicoDataSolutions/finetune#337]
I0722 11:37:40.033967 140025675986688 base.py:104] Saving tensorboard output to /tmp/Finetune_li_plb1
I0722 11:37:54.082098 140025675986688 config.py:78]  Visible GPUs: {0: Tesla K80, 1: Tesla K80, 2: Tesla K80, 3: Tesla K80, 4: Tesla K80, 5: Tesla K80, 6: Tesla K80, 7: Tesla K80}
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-d22e060fad34> in <module>
      1 model = MultiLabelClassifier(n_epochs=3, base_model=GPT2)
----> 2 model.fit(trainX, trainY)

~/.local/lib/python3.5/site-packages/finetune/base.py in fit(self, *args, **kwargs)
    431     def fit(self, *args, **kwargs):
    432         """ An alias for finetune. """
--> 433         return self.finetune(*args, **kwargs)
    434 
    435     def _predict(self, Xs):

~/.local/lib/python3.5/site-packages/finetune/target_models/multi_label_classifier.py in finetune(self, X, Y, batch_size)
     65                            corresponds to the number of training examples provided to each GPU.
     66         """
---> 67         return super().finetune(X, Y=Y, batch_size=batch_size)
     68 
     69     @staticmethod

~/.local/lib/python3.5/site-packages/finetune/base.py in finetune(self, Xs, Y, batch_size)
    152 
    153         force_build_lm = (Y is None)
--> 154         estimator, hooks = self.get_estimator(force_build_lm=force_build_lm)
    155         train_hooks = hooks.copy()
    156 

~/.local/lib/python3.5/site-packages/finetune/base.py in get_estimator(self, force_build_lm, build_explain)
    269 
    270     def get_estimator(self, force_build_lm=False, build_explain=False):
--> 271         config = self._get_estimator_config()
    272 
    273         model_fn = get_model_fn(

~/.local/lib/python3.5/site-packages/finetune/base.py in _get_estimator_config(self)
    254             self.config.per_process_gpu_memory_fraction
    255         )
--> 256         distribute_strategy = self._distribute_strategy(self.config.visible_gpus)
    257         config = tf.estimator.RunConfig(
    258             tf_random_seed=self.config.seed,

~/.local/lib/python3.5/site-packages/finetune/base.py in _distribute_strategy(self, visible_gpus)
    235         if num_gpus > 1:
    236             distribute_strategy = PatchedParameterServerStrategy(
--> 237                 visible_gpus=resolved_gpus
    238             )
    239         elif num_gpus == 1:

~/.local/lib/python3.5/site-packages/finetune/util/estimator.py in __init__(self, visible_gpus)
     71                 self,
     72                 num_gpus_per_worker=len(visible_gpus),
---> 73                 visible_gpus=visible_gpus
     74             )
     75         )

~/.local/lib/python3.5/site-packages/finetune/util/estimator.py in __init__(self, container_strategy, num_gpus_per_worker, visible_gpus)
     14 
     15     def __init__(self, container_strategy, num_gpus_per_worker, visible_gpus):
---> 16         super(ParameterServerExtended, self).__init__(container_strategy)
     17         self._num_gpus_per_worker = num_gpus_per_worker
     18         self._visible_gpus = visible_gpus

/usr/local/lib/python3.5/dist-packages/tensorflow/python/distribute/parameter_server_strategy.py in __init__(self, container_strategy, cluster_resolver, compute_devices, parameter_device)
    129         cluster_resolver=cluster_resolver,
    130         compute_devices=compute_devices,
--> 131         parameter_device=parameter_device)
    132 
    133     # We typically don't need to do all-reduce in this strategy.

/usr/local/lib/python3.5/dist-packages/tensorflow/python/distribute/parameter_server_strategy.py in _initialize_strategy(self, cluster_resolver, compute_devices, parameter_device)
    143     else:
    144       self._initialize_local(
--> 145           compute_devices, parameter_device, cluster_resolver=cluster_resolver)
    146 
    147   def _initialize_multi_worker(self, cluster_resolver):

**Additional context**

**Comment by benleetownsend** [comment]
Can you please confirm your tensorflow version. I believe we do not currently have support for 1.14.* and this looks like it may be related to the problem you are seeing. If in doubt try 1.13.1 or the docker container included in the repo.

**Comment by emtropyml** [comment]
Thanks!
