### ISSUE TITLE
ResourceExhaustedError

### ISSUE THREAD

**Issue by emtropyml** [IndicoDataSolutions/finetune#339]
**Describe the bug**

INFO:finetune:Saving tensorboard output to /tmp/Finetunece1xntyk

Validation:   0%|          | 0/100 [00:00<?, ?it/s]
Validation:  48%|████▊     | 48/100 [00:00<00:00, 122.95it/s]
Validation:  64%|██████▍   | 64/100 [00:00<00:00, 81.44it/s] 
Validation:  80%|████████  | 80/100 [00:01<00:00, 65.88it/s]
Validation:  96%|█████████▌| 96/100 [00:01<00:00, 58.11it/s]
                                                            
Epoch 1/5:   0%|          | 0/10224 [00:00<?, ?it/s]
Epoch 1/5:   0%|          | 28/10224 [00:00<00:36, 275.72it/s]
Epoch 1/5:   1%|          | 93/10224 [00:00<00:30, 333.20it/s]
Epoch 1/5:   2%|▏         | 172/10224 [00:00<00:24, 402.59it/s]
---------------------------------------------------------------------------
ResourceExhaustedError                    Traceback (most recent call last)
~/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py in _do_call(self, fn, *args)
   1333     try:
-> 1334       return fn(*args)
   1335     except errors.OpError as e:

~/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py in _run_fn(feed_dict, fetch_list, target_list, options, run_metadata)
   1318       return self._call_tf_sessionrun(
-> 1319           options, feed_dict, fetch_list, target_list, run_metadata)
   1320 

~/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py in _call_tf_sessionrun(self, options, feed_dict, fetch_list, target_list, run_metadata)
   1406         self._session, options, feed_dict, fetch_list, target_list,
-> 1407         run_metadata)
   1408 

ResourceExhaustedError: OOM when allocating tensor with shape[16,12,512,512] and type float on /job:localhost/replica:0/task:0/device:GPU:2 by allocator GPU_2_bfc
	 [[{{node replica_2/model/featurizer/h8/attn/truediv}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

	 [[{{node replica_3/OptimizeLoss/clip_by_global_norm/mul_45}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

During handling of the above exception, another exception occurred:

ResourceExhaustedError                    Traceback (most recent call last)
<ipython-input-6-24a84feaad30> in <module>
      1 model = MultiLabelClassifier(base_model=GPT2, batch_size=16, multi_label_sequences=True, n_epochs=5, summarize_grads=True)
----> 2 model.fit(trainX, trainY)

~/.local/lib/python3.5/site-packages/finetune/base.py in fit(self, *args, **kwargs)
    431     def fit(self, *args, **kwargs):
    432         """ An alias for finetune. """
--> 433         return self.finetune(*args, **kwargs)
    434 
    435     def _predict(self, Xs):

~/.local/lib/python3.5/site-packages/finetune/target_models/multi_label_classifier.py in finetune(self, X, Y, batch_size)
     65                            corresponds to the number of training examples provided to each GPU.
     66         """
---> 67         return super().finetune(X, Y=Y, batch_size=batch_size)
     68 
     69     @staticmethod

~/.local/lib/python3.5/site-packages/finetune/base.py in finetune(self, Xs, Y, batch_size)
    219 
    220                 tf.logging.info("Finishing pre-fit initialisation...")
--> 221             estimator.train(train_input_fn, hooks=train_hooks, steps=num_steps)
    222 
    223     def _distribute_strategy(self, visible_gpus):

~/.local/lib/python3.5/site-packages/tensorflow_estimator/python/estimator/estimator.py in train(self, input_fn, hooks, steps, max_steps, saving_listeners)
    356 
    357       saving_listeners = _check_listeners_type(saving_listeners)
--> 358       loss = self._train_model(input_fn, hooks, saving_listeners)
    359       logging.info('Loss for final step: %s.', loss)
    360       return self

~/.local/lib/python3.5/site-packages/tensorflow_estimator/python/estimator/estimator.py in _train_model(self, input_fn, hooks, saving_listeners)
   1120   def _train_model(self, input_fn, hooks, saving_listeners):
   1121     if self._train_distribution:
-> 1122       return self._train_model_distributed(input_fn, hooks, saving_listeners)
   1123     else:
   1124       return self._train_model_default(input_fn, hooks, saving_listeners)

~/.local/lib/python3.5/site-packages/tensorflow_estimator/python/estimator/estimator.py in _train_model_distributed(self, input_fn, hooks, saving_listeners)
   1183       self._config._train_distribute.configure(self._config.session_config)
   1184       return self._actual_train_model_distributed(
-> 1185           self._config._train_distribute, input_fn, hooks, saving_listeners)
   1186     # pylint: enable=protected-access
   1187 

~/.local/lib/python3.5/site-packages/tensorflow_estimator/python/estimator/estimator.py in _actual_train_model_distributed(self, strategy, input_fn, hooks, saving_listeners)
   1285         return self._train_with_estimator_spec(estimator_spec, worker_hooks,
   1286                                                hooks, global_step_tensor,
-> 1287                                                saving_listeners)
   1288 
   1289   def _train_with_estimator_spec(self, estimator_spec, worker_hooks, hooks,

~/.local/lib/python3.5/site-packages/tensorflow_estimator/python/estimator/estimator.py in _train_with_estimator_spec(self, estimator_spec, worker_hooks, hooks, global_step_tensor, saving_listeners)
   1405       any_step_done = False
   1406       while not mon_sess.should_stop():
-> 1407         _, loss = mon_sess.run([estimator_spec.train_op, estimator_spec.loss])
   1408         any_step_done = True
   1409     if not any_step_done:

~/.local/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py in run(self, fetches, feed_dict, options, run_metadata)
    674                           feed_dict=feed_dict,
    675                           options=options,
--> 676                           run_metadata=run_metadata)
    677 
    678   def run_step_fn(self, step_fn):

~/.local/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py in run(self, fetches, feed_dict, options, run_metadata)
   1169                               feed_dict=feed_dict,
   1170                               options=options,
-> 1171                               run_metadata=run_metadata)
   1172       except _PREEMPTION_ERRORS as e:
   1173         logging.info('An error was raised. This may be due to a preemption in '

~/.local/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py in run(self, *args, **kwargs)
   1268         raise six.reraise(*original_exc_info)
   1269       else:
-> 1270         raise six.reraise(*original_exc_info)
   1271 
   1272 

~/.local/lib/python3.5/site-packages/six.py in reraise(tp, value, tb)
    691             if value.__traceback__ is not tb:
    692                 raise value.with_traceback(tb)
--> 693             raise value
    694         finally:
    695             value = None

~/.local/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py in run(self, *args, **kwargs)
   1253   def run(self, *args, **kwargs):
   1254     try:
-> 1255       return self._sess.run(*args, **kwargs)
   1256     except _PREEMPTION_ERRORS:
   1257       raise

~/.local/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py in run(self, fetches, feed_dict, options, run_metadata)
   1325                                   feed_dict=feed_dict,
   1326                                   options=options,
-> 1327                                   run_metadata=run_metadata)
   1328 
   1329     for hook in self._hooks:

~/.local/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py in run(self, *args, **kwargs)
   1089 
   1090   def run(self, *args, **kwargs):
-> 1091     return self._sess.run(*args, **kwargs)
   1092 
   1093   def run_step_fn(self, step_fn, raw_session, run_with_hooks):

~/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py in run(self, fetches, feed_dict, options, run_metadata)
    927     try:
    928       result = self._run(None, fetches, feed_dict, options_ptr,
--> 929                          run_metadata_ptr)
    930       if run_metadata:
    931         proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

~/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py in _run(self, handle, fetches, feed_dict, options, run_metadata)
   1150     if final_fetches or final_targets or (handle and feed_dict_tensor):
   1151       results = self._do_run(handle, final_targets, final_fetches,
-> 1152                              feed_dict_tensor, options, run_metadata)
   1153     else:
   1154       results = []

~/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py in _do_run(self, handle, target_list, fetch_list, feed_dict, options, run_metadata)
   1326     if handle is None:
   1327       return self._do_call(_run_fn, feeds, fetches, targets, options,
-> 1328                            run_metadata)
   1329     else:
   1330       return self._do_call(_prun_fn, handle, feeds, fetches)

~/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py in _do_call(self, fn, *args)
   1346           pass
   1347       message = error_interpolation.interpolate(message, self._graph)
-> 1348       raise type(e)(node_def, op, message)
   1349 
   1350   def _extend_graph(self):

ResourceExhaustedError: OOM when allocating tensor with shape[16,12,512,512] and type float on /job:localhost/replica:0/task:0/device:GPU:2 by allocator GPU_2_bfc
	 [[node replica_2/model/featurizer/h8/attn/truediv (defined at /home/jupyter/.local/lib/python3.5/site-packages/finetune/base_models/gpt2/featurizer.py:16) ]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

	 [[node replica_3/OptimizeLoss/clip_by_global_norm/mul_45 (defined at /home/jupyter/.local/lib/python3.5/site-packages/finetune/model.py:221) ]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

Caused by op 'replica_2/model/featurizer/h8/attn/truediv', defined at:
  File "/usr/lib/python3.5/threading.py", line 882, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/home/jupyter/.local/lib/python3.5/site-packages/tensorflow/python/distribute/mirrored_strategy.py", line 852, in run
    self.main_result = self.main_fn(*self.main_args, **self.main_kwargs)
  File "/home/jupyter/.local/lib/python3.5/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1112, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "/home/jupyter/.local/lib/python3.5/site-packages/finetune/model.py", line 110, in _model_fn
    explain=build_explain,
  File "/home/jupyter/.local/lib/python3.5/site-packages/finetune/base_models/__init__.py", line 28, in get_featurizer
    return cls.featurizer(X, encoder, config, train=train, reuse=reuse, **kwargs)
  File "/home/jupyter/.local/lib/python3.5/site-packages/finetune/base_models/gpt2/featurizer.py", line 176, in gpt2_featurizer
    h = block_fn(h)
  File "/home/jupyter/.local/lib/python3.5/site-packages/finetune/base_models/gpt2/featurizer.py", line 108, in block
    a = attn(norm(x, 'ln_1'), 'attn', nx, past=past, hparams=hparams, train=train)
  File "/home/jupyter/.local/lib/python3.5/site-packages/finetune/base_models/gpt2/featurizer.py", line 90, in attn
    a = multihead_attn(q, k, v, hparams.attn_p_drop, train=train)
  File "/home/jupyter/.local/lib/python3.5/site-packages/finetune/base_models/gpt2/featurizer.py", line 78, in multihead_attn
    w = softmax(w)
  File "/home/jupyter/.local/lib/python3.5/site-packages/finetune/base_models/gpt2/featurizer.py", line 16, in softmax
    return ex / tf.reduce_sum(ex, axis=axis, keepdims=True)
  File "/home/jupyter/.local/lib/python3.5/site-packages/tensorflow/python/ops/math_ops.py", line 812, in binary_op_wrapper
    return func(x, y, name=name)
  File "/home/jupyter/.local/lib/python3.5/site-packages/tensorflow/python/ops/math_ops.py", line 920, in _truediv_python3
    return gen_math_ops.real_div(x, y, name=name)
  File "/home/jupyter/.local/lib/python3.5/site-packages/tensorflow/python/ops/gen_math_ops.py", line 6897, in real_div
    "RealDiv", x=x, y=y, name=name)
  File "/home/jupyter/.local/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/home/jupyter/.local/lib/python3.5/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/jupyter/.local/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 3300, in create_op
    op_def=op_def)
  File "/home/jupyter/.local/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[16,12,512,512] and type float on /job:localhost/replica:0/task:0/device:GPU:2 by allocator GPU_2_bfc
	 [[node replica_2/model/featurizer/h8/attn/truediv (defined at /home/jupyter/.local/lib/python3.5/site-packages/finetune/base_models/gpt2/featurizer.py:16) ]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

	 [[node replica_3/OptimizeLoss/clip_by_global_norm/mul_45 (defined at /home/jupyter/.local/lib/python3.5/site-packages/finetune/model.py:221) ]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

**Minimum Reproducible Example**
A short code snippet which reproduces the exception
model = MultiLabelClassifier(base_model=GPT2, batch_size=16, multi_label_sequences=True, n_epochs=5, summarize_grads=True)
model.fit(trainX, trainY)

**Expected behavior**

**Additional context**

**Comment by benleetownsend** [comment]
This is simply that your GPU memory cannot handle a batch size of 16. There are a few things to consider here and I recommend trying them in this order.

1) We have found that very few tasks actually benefit performance-wise from the large batch size. So starting with the default batch size of 2 and benchmarking this is very likely to yield good results.
2) The batch size here is per-gpu. It appears you are maybe using multiple GPUs here. So if you intended on a global batch size of 16 and you have 4 GPUS you want to set batch_size=4. 
3) If you absolutely require the large batch sizes, then setting low_memory_mode=True will turn on gradient checkpointing and allow larger batch sizes to fit in memory.
4) If the text is consistently shorter than the default 512 tokens long. You can set the max_length parameter. Transformers have a memory complexity of `O(max_length ** 2)` so this can make a large improvement to memory footprint.`

Hopefully one of these options gives you some success. If you require further assistance let me know.

**Comment by benleetownsend** [comment]
Did any of this help??

**Comment by emtropyml** [comment]
Yeah, Thanks! Although I'm wondering what would be an ideal machine configuration to carry out larger experiments. I'm already using 32 vCPUs, 208 GB RAM.

**Comment by benleetownsend** [comment]
It really depends what you plan to be doing with finetune. For most things a modest machine much smaller than the one you described and a modern(ish) GPU with > 8GB memory should be more than enough. It really depends how you define "Larger".

**Comment by benleetownsend** [comment]
To be clear, the traceback you posted above is showing GPU memory exhaustion not CPU RAM. ```
ResourceExhaustedError: OOM when allocating tensor with shape[16,12,512,512] and type float on /job:localhost/replica:0/task:0/device:GPU:2 by allocator GPU_2_bfc```

**Comment by emtropyml** [comment]
I guess 4 NVIDIA Tesla P100 GPUs don't seem to be good enough!

**Comment by madisonmay** [comment]
Hi @emtropyml -- just drop your batch size down a bit and you should be fine.  Try a batch size of 2-4.
