### ISSUE TITLE
`lr_warmup` parameter doesn't seem to get used

### ISSUE THREAD

**Issue by khoa-ho** [IndicoDataSolutions/finetune#373]
I experimented with `lr_warmup` but didn't see any change to that parameter in Tensorboard. The source code here https://github.com/IndicoDataSolutions/finetune/blob/master/finetune/model.py#L206 seems to validate my suspiscion.

**Comment by madisonmay** [comment]
Hi again @khoa-ho -- thank you again for the bug report!  Took a peek at your link and can confirm that this value is no longer used.  Will dig back through the commit logs and repair it!

**Comment by madisonmay** [comment]
Fix up at #374. Will merge after quick review -- need to consider what the defaults should be now that this is again functional.  Will go out to PyPI as part of the 0.8.3 release but you use it from that branch for now. Thanks again!

**Comment by khoa-ho** [comment]
@madisonmay Thank you, I'll test it out!

**Comment by madisonmay** [comment]
Sounds good!  Closing this issue for now, feel free to re-open if you have further issues!
