### ISSUE TITLE
model.featurize_sequence()

### ISSUE THREAD

**Issue by rnyak** [IndicoDataSolutions/finetune#390]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

Can you provide an example for the featurize_sequence(*args, **kwargs) 

what are the args we can give to this function?

**Describe alternatives you've considered**

**Additional context**

**Comment by madisonmay** [comment]
Hi @rynak!  Thanks for the bug report. 

I'll roll this into our documentation shortly, but the gist is that the `sequence_features()` method provides you with access to the output of the final transformer layer before pooling.

Example:

```
from finetune import Classifier
model = Classifier()
sequence_features = model.featurize_sequence(["Featurize sequence outputs a vector per token"])
print(sequence_features.shape)
# outputs (1, 512, 768) or more generically (n_examples, max_length, hidden_dim)
```

**Comment by madisonmay** [comment]
We have some minimal documentation as part of the API reference now -- https://finetune.indico.io/api.html#finetune.Classifier.featurize_sequence.  Hopefully we'll offer some more fully featured examples here eventually, but I think that'll do for now.  Closing this issue, but feel free to open another if you have further questions!
