### ISSUE TITLE
The S3 bucket hosting the models not accessible

### ISSUE THREAD

**Issue by skomban** [IndicoDataSolutions/finetune#395]
Currently the S3 bucket `https://s3.amazonaws.com/bendropbox` is not accessible. Is there any other way to access those models? Thanks.

**Comment by madisonmay** [comment]
Ah ok!  This makes more sense.  It seems likely that you're missing a certificate on your end -- I'm going to guess you're on OSX on Python 3.6?  If so, running `/Applications/Python 3.6/Install Certificates.command` should do the trick.

**Comment by benleetownsend** [comment]
@skomban Did this solve your problem?

**Comment by madisonmay** [comment]
Closing as this is most likely an issue with SSL cert setup rather than S3 bucket permissioning.
