### ISSUE TITLE
Tensorflow-gpu version

### ISSUE THREAD

**Issue by rnyak** [IndicoDataSolutions/finetune#396]
Hi,

I am running finetune on gpu, and currently using finetune docker container.  The tf-gpu version in the docker file is 1.14.0.
exp:
`FROM tensorflow/tensorflow:1.14.0-gpu-py3` 

However, in the README, under Installation section, It reads as "In order to run finetune on your host, you'll need a working copy of CUDA >= 8.0, libcudnn >= 6, **tensorflow-gpu >= 1.6** and up to date nvidia-driver versions."

Is the docker file not updated yet? Or it is fine to run with the tf-gpu 1.14.0 version?

Thanks.

**Comment by benleetownsend** [comment]
Tensorflow 1.14 is the correct version. This is a documentation issue. Thanks for pointing this out.

**Comment by madisonmay** [comment]
Resolved by #397 

Thanks @rnyak!
