### ISSUE TITLE
add support for custom pre-trained models

### ISSUE THREAD

**Issue by yurakuratov** [IndicoDataSolutions/finetune#398]
Hi!

Currently, finetune supports only predefined list of pre-trained models. For example, for BERT you have BERTModelCased, BERTModelLargeCased, BERTModelLargeWWMCased, BERTModelMultilingualCased. Vocabulary, config and pre-trained weights are hardcoded in [model.py](https://github.com/IndicoDataSolutions/finetune/blob/master/finetune/base_models/bert/model.py). 

I have tensorflow checkpoint (compatible with original Google pre-trained checkpoints), config and vocab files for my custom pre-trained BERT-base model.
How can I use it with finetune?

Desired solution may look like this:
```
base_model_configuration = {'vocab': path_to_vocab, 
                            'config': path_to_config, 
                            'checkpoint': path_to_checkpoint,
                            'lowercase': False}
}
model = Classifier(base_model=BERT, base_model_config=base_model_configuration)
```

**Comment by benleetownsend** [comment]
Thanks for the request. We will look into making this easier in the future. For now unfortunately it will require a bit of manual work.

First to convert the checkpoint into our format, you can use the following script.

```
import tensorflow as tf
import joblib  as jl

INPUT_CHECKPOINT = ...
OUTPUT_NAME = ...

reader = tf.train.NewCheckpointReader(INPUT_CHECKPOINT)
keys = list(reader.get_variable_to_shape_map().keys())
output_dict = {'model/featurizer/' + k + ":0": reader.get_tensor(k) for k in keys}
jl.dump(output_dict, OUTPUT_NAME)
```
Assuming that the vocab and config is the same as one of the original BERT models we have this would then be as simple as pointing the model to the new file with.

```
from finetune import Classifier

Classifier(base_model=BERT, base_model_path=OUTPUT_NAME)
```

Replacing BERT for whichever your model is based off. If this does not work for you and you have modified the vocab and/or config then you'll need to do the following.


```
from finetune.base_models.bert.encoder import BERTEncoder
from finetune.base_models import SourceModel
from finetune.base_models.bert.featurizer import bert_featurizer

VOCAB_PATH = ...
IS_LOWER = ...

class MyBERTEncoder(BERTEncoder):
    def __init__(
        self, encoder_path=None, vocab_path=VOCAB_PATH, lower_case=IS_LOWER
    ):
        super().__init__(
            encoder_path=encoder_path, vocab_path=vocab_path, lower_case=lower_case
        )

class MyBERTModel(SourceModel):
    is_bidirectional = True
    encoder = MyBERTEncoder
    featurizer = bert_featurizer
    settings = {
        "n_embed": 768,
        "n_epochs": 8,
        "n_heads": 12,
        "n_layer": 12,
        "act_fn": "gelu",
        "lr_warmup": 0.1,
        "lr": 1e-5,
        "l2_reg": 0.01,
        "bert_intermediate_size": 3072,
        "base_model_path": OUTPUT_NAME,
    }
    required_files = []
```
You'll need to set paths and config items in the above to be the same as in your BERT config. We don't have documentation on how the hyper-parameter names map across, let me know if you cant figure any of it out. 

Then you should just be able to instantiate the model with
```
from finetune import Classifier
model = Classifier(base_model=MyBERTModel)
...
```

Let me know if this doesn't work for you or you have any other questions.

**Comment by yurakuratov** [comment]
Thank you, it worked!

**Comment by benleetownsend** [comment]
Glad to hear it!
