### ISSUE TITLE
FinetuneError: Unexpected setting configuration: `_threshold` is an invalid keyword. Did you mean `tasks`?

### ISSUE THREAD

**Issue by emtropyml** [IndicoDataSolutions/finetune#400]
FinetuneError                             Traceback (most recent call last)
<ipython-input-2-0100bc4f306d> in <module>
----> 1 **model = MultiLabelClassifier.load('comp_DB.model') #DistilBERT model**

~/.local/lib/python3.5/site-packages/finetune/base.py in load(path, *args, **kwargs)
    721 
    722         saver = Saver()
--> 723         model = saver.load(path)
    724 
    725         # Backwards compatability

~/.local/lib/python3.5/site-packages/finetune/saver.py in load(self, path)
    229     def load(self, path):
    230         self.variables, finetune_obj = joblib.load(path)
--> 231         finetune_obj.config = get_config(**dict(finetune_obj.config))
    232         return finetune_obj
    233 

~/.local/lib/python3.5/site-packages/finetune/config.py in get_config(**kwargs)
    366     :param **kwargs: Keyword arguments to override default values.
    367     :return: Config object.    """
--> 368     assert_valid_config(**kwargs)
    369     config = get_default_config()
    370     config.base_model = kwargs.get("base_model", config.base_model)

~/.local/lib/python3.5/site-packages/finetune/config.py in assert_valid_config(**kwargs)
    227             raise FinetuneError(
    228                 "Unexpected setting configuration: `{}` is an invalid keyword. "
--> 229                 "Did you mean `{}`?".format(kwarg, did_you_mean(kwarg, expected_keys))
    230             )
    231 

**FinetuneError: Unexpected setting configuration: `_threshold` is an invalid keyword. Did you mean `tasks`?**

**Comment by madisonmay** [comment]
Taking a look!  We think we understand what's going on here, just need to decide how to resolve it.  Definitely a bug though, thanks for the report.

**Comment by madisonmay** [comment]
I have a preliminary fix up at #401 

Should be on development soon!

**Comment by madisonmay** [comment]
@emtropyml patch is now on development.  Will also go out on PyPI as part of 0.8.4.  Thanks again for the report, let me know if your issue persists!

**Comment by madisonmay** [comment]
I think this is resolved since our most recent minor release, so going to go ahead and close this!
