### ISSUE TITLE
ValueError: Couldn't find trained model at /tmp/Finetune14yvac9b.

### ISSUE THREAD

**Issue by emtropyml** [IndicoDataSolutions/finetune#402]
**Describe the bug**
INFO:finetune:Saving tensorboard output to /tmp/Finetune14yvac9b

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-22-d15dcc8cabf8> in <module>
      6     inputs = {"x": tf.placeholder(shape=xshapes, dtype=xtypes)}
      7     return tf.estimator.export.ServingInputReceiver(inputs, inputs)
----> 8 estimator.export_saved_model(export_dir_base='saved_model', serving_input_receiver_fn=serving_input_receiver_fn)

~/.local/lib/python3.5/site-packages/tensorflow_estimator/python/estimator/estimator.py in export_saved_model(self, export_dir_base, serving_input_receiver_fn, assets_extra, as_text, checkpoint_path, experimental_mode)
    730         as_text=as_text,
    731         checkpoint_path=checkpoint_path,
--> 732         strip_default_attrs=True)
    733 
    734   def experimental_export_all_saved_models(

~/.local/lib/python3.5/site-packages/tensorflow_estimator/python/estimator/estimator.py in _export_all_saved_models(self, export_dir_base, input_receiver_fn_map, assets_extra, as_text, checkpoint_path, strip_default_attrs)
    825         else:
    826           raise ValueError("Couldn't find trained model at {}.".format(
--> 827               self._model_dir))
    828 
    829       export_dir = export_lib.get_timestamped_export_dir(export_dir_base)

**ValueError: Couldn't find trained model at /tmp/Finetune14yvac9b.**

**Minimum Reproducible Example**
from finetune import MultiLabelClassifier
model = MultiLabelClassifier.load('comp_gpt2.model')
estimator, hooks = model.get_estimator()
(xtypes, ytypes), (xshapes, yshapes) = model.input_pipeline.feed_shape_type_def()
def serving_input_receiver_fn():
    inputs = {"x": tf.placeholder(shape=xshapes, dtype=xtypes)}
    return tf.estimator.export.ServingInputReceiver(inputs, inputs)
estimator.export_saved_model(export_dir_base='saved_model', serving_input_receiver_fn=serving_input_receiver_fn)

**Comment by benleetownsend** [comment]
You will need to modify get_estimator to re-enable the default savers as we use a custom saver setup. https://github.com/IndicoDataSolutions/finetune/blob/df13020fc826fab9b90ba7f98b2cfe634833e006/finetune/base.py#L303.

**Comment by emtropyml** [comment]
Could you please elaborate on specifically what changes I need to make? Thanks!

**Comment by emtropyml** [comment]
@benleetownsend @madisonmay Could you please specify this? Thanks.

**Comment by benleetownsend** [comment]
@emtropyml If you set `save_checkpoints_steps=100` for example you will re-enable the saver and you should then be able to find the saved model in that file.

**Comment by emtropyml** [comment]
Thanks @benleetownsend . But after trying this I'm getting another error:
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~/.local/lib/python3.5/site-packages/tensorflow/python/eager/execute.py in make_type(v, arg_name)
    127   try:
--> 128     v = dtypes.as_dtype(v).base_dtype
    129   except TypeError:

~/.local/lib/python3.5/site-packages/tensorflow/python/framework/dtypes.py in as_dtype(type_value)
    711   try:
--> 712     return _ANY_TO_TF[type_value]
    713   except KeyError:

TypeError: unhashable type: 'dict'

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
<ipython-input-8-c0db65a05cc6> in <module>
----> 1 estimator.export_saved_model(export_dir_base='saved_model', serving_input_receiver_fn=serving_input_receiver_fn)

~/.local/lib/python3.5/site-packages/tensorflow_estimator/python/estimator/estimator.py in export_saved_model(self, export_dir_base, serving_input_receiver_fn, assets_extra, as_text, checkpoint_path, experimental_mode)
    730         as_text=as_text,
    731         checkpoint_path=checkpoint_path,
--> 732         strip_default_attrs=True)
    733 
    734   def experimental_export_all_saved_models(

~/.local/lib/python3.5/site-packages/tensorflow_estimator/python/estimator/estimator.py in _export_all_saved_models(self, export_dir_base, input_receiver_fn_map, assets_extra, as_text, checkpoint_path, strip_default_attrs)
    854             builder, input_receiver_fn_map, checkpoint_path,
    855             save_variables, mode=ModeKeys.PREDICT,
--> 856             strip_default_attrs=strip_default_attrs)
    857         save_variables = False
    858 

~/.local/lib/python3.5/site-packages/tensorflow_estimator/python/estimator/estimator.py in _add_meta_graph_for_mode(self, builder, input_receiver_fn_map, checkpoint_path, save_variables, mode, export_tags, check_variables, strip_default_attrs)
    920       random_seed.set_random_seed(self._config.tf_random_seed)
    921 
--> 922       input_receiver = input_receiver_fn()
    923 
    924       # Call the model_fn and collect the export_outputs.

<ipython-input-6-f52311fb22e1> in serving_input_receiver_fn()
      2 (xtypes, ytypes), (xshapes, yshapes) = model.input_pipeline.feed_shape_type_def()
      3 def serving_input_receiver_fn():
----> 4     inputs = {"x": tf.placeholder(shape=xshapes, dtype=xtypes)}
      5     return tf.estimator.export.ServingInputReceiver(inputs, inputs)

~/.local/lib/python3.5/site-packages/tensorflow/python/ops/array_ops.py in placeholder(dtype, shape, name)
   2141                        "eager execution.")
   2142 
-> 2143   return gen_array_ops.placeholder(dtype=dtype, shape=shape, name=name)
   2144 
   2145 

~/.local/lib/python3.5/site-packages/tensorflow/python/ops/gen_array_ops.py in placeholder(dtype, shape, name)
   6255       _six.raise_from(_core._status_to_exception(e.code, message), None)
   6256   # Add nodes to the TensorFlow graph.
-> 6257   dtype = _execute.make_type(dtype, "dtype")
   6258   if shape is None:
   6259     shape = None

~/.local/lib/python3.5/site-packages/tensorflow/python/eager/execute.py in make_type(v, arg_name)
    129   except TypeError:
    130     raise TypeError("Expected DataType for argument '%s' not %s." %
--> 131                     (arg_name, repr(v)))
    132   i = v.as_datatype_enum
    133   return i

TypeError: Expected DataType for argument 'dtype' not {'tokens': tf.int32, 'mask': tf.float32}.

**Comment by emtropyml** [comment]
I've used the following code:

class NewMultiLabelClassifier(MultiLabelClassifier):
    def _get_estimator_config(self):
        conf = tf.ConfigProto(
            allow_soft_placement=self.config.soft_device_placement,
            log_device_placement=self.config.log_device_placement,
        )
        if self.config.per_process_gpu_memory_fraction is not None:
            conf.gpu_options.per_process_gpu_memory_fraction = (
                self.config.per_process_gpu_memory_fraction
            )
        distribute_strategy = self._distribute_strategy(self.config.visible_gpus)
        config = tf.estimator.RunConfig(
            tf_random_seed=self.config.seed,
            save_summary_steps=self.config.val_interval,
            save_checkpoints_secs=600,
            save_checkpoints_steps=None,
            # disable auto summaries
            session_config=conf,
            log_step_count_steps=100,
            train_distribute=distribute_strategy,
            keep_checkpoint_max=1,
        )
        return config

model = NewMultiLabelClassifier(base_model=DistilBERT, batch_size=2, chunk_long_sequences=False, multi_label_sequences=True, n_epochs=3)
model.fit(trainX, trainY)

estimator, hooks = model.get_estimator()
(xtypes, ytypes), (xshapes, yshapes) = model.input_pipeline.feed_shape_type_def()
def serving_input_receiver_fn():
inputs = {"x": tf.placeholder(shape=xshapes, dtype=xtypes)}
return tf.estimator.export.ServingInputReceiver(inputs, inputs)
estimator.export_saved_model(export_dir_base='saved_model', serving_input_receiver_fn=serving_input_receiver_fn)

**Comment by benleetownsend** [comment]
I'm not exactly sure since I haven't tried to export a finetune model like this before.

However, it seems like the traceback is saying:
 `{"x": tf.placeholder(shape=xshapes, dtype=xtypes)` 
is invalid as placeholder takes a shape and a dtype, not a dict, so I would guess that you'd want something like:
 `{k: tf.placeholder(shape=xshapes[k], dtype=xtypes[k]) for k in xshapes.keys()}`

**Comment by madisonmay** [comment]
Something like [BentoML](https://github.com/bentoml/BentoML) could possibly work to make your life deploying finetune models easier?

**Comment by emtropyml** [comment]
What would be the Finetune Model Artifact for BentoML? 

How can we deploy Finetune Model on AWS Sagemaker instead?

**Comment by benleetownsend** [comment]
As previously stated in your issue #345 any attempt to use one of the frameworks that requires exporting the graph (such as AWS Sagemaker) will require manual deconstruction of all the pre-processing and post processing code to allow correctly formatting inputs to the model, and the outputs of the model to predictions. This it is not something we are looking to support ourselves.

I would suggest that the simple suggestion @madisonmay made in your issue #392 is a very good one and seems like it could give the basis for an implementation with BentoML but I am unfamiliar with the details of that library. 

Going to close this issue for now, feel free to reopen if you have further questions.
