### ISSUE TITLE
Will English text be piece-cut in this project?

### ISSUE THREAD

**Issue by c0derm4n** [IndicoDataSolutions/finetune#403]
**Describe the bug**

**Minimum Reproducible Example**
A short code snippet which reproduces the exception

**Expected behavior**

**Additional context**

when i use Bert as Classifier, will  the input text use "wordpiece_tokenizer"? or just cutted by space?

**Comment by madisonmay** [comment]
BERT does use the wordpiece tokenizer. See: https://github.com/IndicoDataSolutions/finetune/blob/development/finetune/base_models/bert/tokenizer.py#L177

**Comment by c0derm4n** [comment]
When i check the code,     Classifier(base_model=RoBERTa)   will use class RoBERTaEncoder(GPT2Encoder) to encode the input text, which is  not related to the wordpiece tokenizer mentioned above. Am i right?
