### ISSUE TITLE
Multilabel classification techniques

### ISSUE THREAD

**Issue by rnyak** [IndicoDataSolutions/finetune#410]
**Is your feature request related to a problem? Please describe.**

It is not clear to me what multi-label classification technique is applied when we use MultiLabelClassifier. I could not find enough info on that. The technique used is OnevsRest, Binary Relevance, Classifier Chains or something else? Is the multi-label classification problem treated as N independent binary classifiers without considering the dependencies between the labels ?

**Describe the solution you'd like**
It'd be informative to see more information on what technique is applied for MultiLabelClassifier in the docs.

**Describe alternatives you've considered**

**Additional context**

**Comment by madisonmay** [comment]
@rnyak we currently treat multi-label classification as N independent binary classifiers that operate on a shared representation. 

Core implementation is available here: 
https://github.com/IndicoDataSolutions/finetune/blob/development/finetune/nn/target_blocks.py#L171

**Comment by madisonmay** [comment]
@rnyak and we can absolutely update the docs to make that more transparent.  Thanks for the suggestion!

**Comment by benleetownsend** [comment]
I believe has now been resolved.
