### ISSUE TITLE
TypeError: unorderable types: float() > NoneType()

### ISSUE THREAD

**Issue by emtropyml** [IndicoDataSolutions/finetune#415]
Inference: 100%|██████████| 1932/1932 [00:18<00:00, 106.11it/s]

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-4-d577ffee3f45> in <module>
      1 mlb = MultiLabelBinarizer()
----> 2 predictions =model.predict(testX)
      3 print(classification_report(mlb.fit_transform(testY),mlb.fit_transform(predictions)))
      4 print(roc_auc_score(mlb.fit_transform(testY), pd.DataFrame(model.predict_proba(testX)).values, average=None))
      5 print(roc_auc_score(mlb.fit_transform(testY), pd.DataFrame(model.predict_proba(testX)).values, average='micro'))

~/.local/lib/python3.5/site-packages/finetune/target_models/multi_label_classifier.py in predict(self, X, threshold)
     59                 # last chunk in a document
     60                 means = np.mean(doc_probs, axis=0)
---> 61                 label = self.input_pipeline.label_encoder.inverse_transform(np.expand_dims(means, 0) > threshold)[0]
     62                 all_labels.append(list(label))
     63         return all_labels

**TypeError: unorderable types: float() > NoneType()**

**Comment by benleetownsend** [comment]
Thanks for the bug report. It seems it is not correctly using the threshold from config. We will push a fix as soon as possible but for now it should work if you call predict with the explicit keyword argument `threshold=` the default was previously 0.5.
