### ISSUE TITLE
Is the pip wheel for 0.8.5 coming soon?

### ISSUE THREAD

**Issue by khoa-ho** [IndicoDataSolutions/finetune#422]
Installing from source doesn't seem to work this time. There's no obvious error but `finetune` was not installed.

**Comment by madisonmay** [comment]
Hrmmm... interesting. Sorry for the delay! We will have the pip wheel up tomorrow morning :)

**Comment by madisonmay** [comment]
If you have more details on the installation difficulties would be happy to help debug.

**Comment by madisonmay** [comment]
0.8.5 should be live!  Let me know if you still encounter issues.

**Comment by khoa-ho** [comment]
Yeah, installation with pip works perfectly. Thanks a lot!
