### ISSUE TITLE
ValueError: EOF: reading array data, expected 262144 bytes got 258324

### ISSUE THREAD

**Issue by emtropyml** [IndicoDataSolutions/finetune#429]
Error loading DistilBERT compiled model file.

(deploy-dl-production) [ec2-user@ip-172-31-25-196 production-deployment]$ python3 infe                                                                                  r_absa.py
/home/ec2-user/anaconda3/envs/deploy-dl-production/lib/python3.7/site-packages/tensorf                                                                                  low/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a s                                                                                  ynonym of type is deprecated; in a future version of numpy, it will be understood as (                                                                                  type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/ec2-user/anaconda3/envs/deploy-dl-production/lib/python3.7/site-packages/tensorf                                                                                  low/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a s                                                                                  ynonym of type is deprecated; in a future version of numpy, it will be understood as (                                                                                  type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/ec2-user/anaconda3/envs/deploy-dl-production/lib/python3.7/site-packages/tensorf                                                                                  low/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a s                                                                                  ynonym of type is deprecated; in a future version of numpy, it will be understood as (                                                                                  type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/ec2-user/anaconda3/envs/deploy-dl-production/lib/python3.7/site-packages/tensorf                                                                                  low/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a s                                                                                  ynonym of type is deprecated; in a future version of numpy, it will be understood as (                                                                                  type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/ec2-user/anaconda3/envs/deploy-dl-production/lib/python3.7/site-packages/tensorf                                                                                  low/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a s                                                                                  ynonym of type is deprecated; in a future version of numpy, it will be understood as (                                                                                  type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/ec2-user/anaconda3/envs/deploy-dl-production/lib/python3.7/site-packages/tensorf                                                                                  low/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a s                                                                                  ynonym of type is deprecated; in a future version of numpy, it will be understood as (                                                                                  type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
/home/ec2-user/anaconda3/envs/deploy-dl-production/lib/python3.7/site-packages/tensorb                                                                                  oard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type'                                                                                   as a synonym of type is deprecated; in a future version of numpy, it will be understo                                                                                  od as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/ec2-user/anaconda3/envs/deploy-dl-production/lib/python3.7/site-packages/tensorb                                                                                  oard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type'                                                                                   as a synonym of type is deprecated; in a future version of numpy, it will be understo                                                                                  od as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/ec2-user/anaconda3/envs/deploy-dl-production/lib/python3.7/site-packages/tensorb                                                                                  oard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type'                                                                                   as a synonym of type is deprecated; in a future version of numpy, it will be understo                                                                                  od as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/ec2-user/anaconda3/envs/deploy-dl-production/lib/python3.7/site-packages/tensorb                                                                                  oard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type'                                                                                   as a synonym of type is deprecated; in a future version of numpy, it will be understo                                                                                  od as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/ec2-user/anaconda3/envs/deploy-dl-production/lib/python3.7/site-packages/tensorb                                                                                  oard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type'                                                                                   as a synonym of type is deprecated; in a future version of numpy, it will be understo                                                                                  od as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/ec2-user/anaconda3/envs/deploy-dl-production/lib/python3.7/site-packages/tensorb                                                                                  oard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type'                                                                                   as a synonym of type is deprecated; in a future version of numpy, it will be understo                                                                                  od as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
WARNING:tensorflow:From /home/ec2-user/anaconda3/envs/deploy-dl-production/lib/python3                                                                                  .7/site-packages/tensorflow_estimator/python/estimator/api/_v1/estimator/__init__.py:1                                                                                  0: The name tf.estimator.inputs is deprecated. Please use tf.compat.v1.estimator.input                                                                                  s instead.

Traceback (most recent call last):
  File "infer_absa.py", line 12, in <module>
    model = MultiLabelClassifier.load('DB128.model')
  File "/home/ec2-user/anaconda3/envs/deploy-dl-production/lib/python3.7/site-packages                                                                                  /finetune/base.py", line 663, in load
    model = saver.load(path)
  File "/home/ec2-user/anaconda3/envs/deploy-dl-production/lib/python3.7/site-packages                                                                                  /finetune/saver.py", line 230, in load
    self.variables, finetune_obj = joblib.load(path)
  File "/home/ec2-user/anaconda3/envs/deploy-dl-production/lib/python3.7/site-packages                                                                                  /joblib/numpy_pickle.py", line 605, in load
    obj = _unpickle(fobj, filename, mmap_mode)
  File "/home/ec2-user/anaconda3/envs/deploy-dl-production/lib/python3.7/site-packages                                                                                  /joblib/numpy_pickle.py", line 529, in _unpickle
    obj = unpickler.load()
  File "/home/ec2-user/anaconda3/envs/deploy-dl-production/lib/python3.7/pickle.py", l                                                                                  ine 1085, in load
    dispatch[key[0]](self)
  File "/home/ec2-user/anaconda3/envs/deploy-dl-production/lib/python3.7/site-packages                                                                                  /joblib/numpy_pickle.py", line 355, in load_build
    self.stack.append(array_wrapper.read(self))
  File "/home/ec2-user/anaconda3/envs/deploy-dl-production/lib/python3.7/site-packages                                                                                  /joblib/numpy_pickle.py", line 198, in read
    array = self.read_array(unpickler)
  File "/home/ec2-user/anaconda3/envs/deploy-dl-production/lib/python3.7/site-packages                                                                                  /joblib/numpy_pickle.py", line 149, in read_array
    read_size, "array data")
  File "/home/ec2-user/anaconda3/envs/deploy-dl-production/lib/python3.7/site-packages                                                                                  /joblib/numpy_pickle_utils.py", line 243, in _read_bytes
    raise ValueError(msg % (error_template, size, len(data)))
**ValueError: EOF: reading array data, expected 262144 bytes got 258324**

**Comment by benleetownsend** [comment]
Can you try:
```
import joblib as jl
jl.load("DB128.model") # replace this to the path to the file.
```
If this does not work, is it possible that your version of Numpy/Pickle/Joblib as changed between when the model was saved and when it was loaded?

@madisonmay might be able to comment more on whether we are expecting to be compatible with python3.7? I have not personally tried it but I see no reason why it should not work.

I would check that the file you saved can be loaded as above in exactly the same environment that it was created. If it cannot then it seems possible that the file was only part copied or corrupted in some other way. If it can then it seems there is some compatibility issues somewhere between the environment that it was created and the environment you are loading. 

If after following these steps you are able to re-produce a save/load that causes this error then if you could send over a script/file and environment details (preferably our docker container) to re-produce then I will be able to look into it.

**Comment by emtropyml** [comment]
Thanks for the insights!

The file was corrupted.
