### ISSUE TITLE
KeyError: 'NORM'

### ISSUE THREAD

**Issue by emtropyml** [IndicoDataSolutions/finetune#445]
The .predict() function is running fine on development server but when I deploy it using a Docker container, I'm getting the following error:

**ERROR:flask.app:Exception on /getcompetencies [POST]**
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/app/app.py", line 119, in get_competencies
    output = calculate_absa(pos_review, neg_review)
  File "/var/app/app.py", line 39, in calculate_absa
    comp = model.predict([pos_review, neg_review],  threshold=0.5)
  File "/usr/local/lib/python3.7/site-packages/finetune/target_models/multi_label_classifier.py", line 51, in predict
    for _, start_of_doc, end_of_doc, _, proba in self.process_long_sequence(X):
  File "/usr/local/lib/python3.7/site-packages/finetune/base.py", line 813, in process_long_sequence
    normal_pred = pred[PredictMode.NORMAL]
**KeyError: 'NORM'**

**Comment by benleetownsend** [comment]
Can you provide a minimum reproducible example? 
I have seen errors similar to this in older versions of finetune when inference is called on an untrained model. But this should've been replaced with a more explicit error in recent versions.

**Comment by emtropyml** [comment]
Here's a minimum reproducible example: 
(I've deployed this using Docker)

import flask
from flask import request, jsonify
from flask_cors import CORS, cross_origin
app = flask.Flask(__name__)
CORS(app)
app.config['CORS_HEADERS'] = 'Content-Type'

from finetune import MultiLabelClassifier

model = MultiLabelClassifier.load('DB128.model')

model._cached_predict = True 

def calculate_out(text):
    out = model.predict(text, threshold=0.5)[0]
    return out

@app.route('/', methods=['GET'])
@cross_origin()
def home():
    return '''<h1>Hello world!</h1>'''

@app.route('/getoutput', methods=['GET', 'POST'])
@cross_origin()
def get_output():
    if request.method == 'POST':
        data = request.get_json()
        text = data["text"]
        text=text.strip()
        output = calculate_out(text)
    else:
        return "Error: No text field provided. Please specify a text."
    return jsonify(output)

if __name__ == '__main__':
    app.run(host="0.0.0.0", debug=False)
    # app.run(host="0.0.0.0", port=80,debug=False)

**Comment by madisonmay** [comment]
Edited your comment slightly to preserve formatting.  Going to try to reproduce.

Would be nice to know the git hash you're working off of and if you think the finetune version the base model was trained on would differ from that.

**Comment by madisonmay** [comment]
If you're working inside of a docker container, the output of 

```bash
pip3 show
``` 

would be helpful.

**Comment by benleetownsend** [comment]
This is likely not the cause of your problem, but it should be `out = model.predict([text], threshold=0.5)[0]` You need to input a list else finetune seems like it will unpack the string.

**Comment by benleetownsend** [comment]
Any updates on this?

**Comment by emtropyml** [comment]
As weird as it sounds, without any changes to the code this error occurs randomly some of the times and some other times it doesn't. I couldn't diagnose it but just got rid of it by chance.
