### ISSUE TITLE
finetune install error

### ISSUE THREAD

**Issue by rnyak** [IndicoDataSolutions/finetune#457]
**Describe the bug**
I am installing finetune on ubuntu 18.04 with `pip3 install finetune` command as instructed on the README, but getting the following error:

```
Collecting finetune
  Using cached https://files.pythonhosted.org/packages/e0/88/534e2d70e2c192791a62b7f118ab6c72d382b2b9401a1460918195d27d89/finetune-0.8.5.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ModuleNotFoundError: No module named 'setuptools'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-n3rm54yi/finetune/

```
when I run the same command `pip3 install finetune` inside the TF container, installation is completed, but no `finetune` folder appears.

**Minimum Reproducible Example**
A short code snippet which reproduces the exception

**Expected behavior**

**Additional context**

**Comment by madisonmay** [comment]
You'll first have to install python3-setuptools (from apt-get). It's a common dependency but not something we can list in the setup.py file because it's used in the setup.py file.

**Comment by rnyak** [comment]
I did. It installed but I do not see the`finetune` folder. Where is it supposed to install the finetune folder? I do not get such issue if I used finetune docker image.

**Comment by madisonmay** [comment]
Ah, it should end up in /usr/local/lib/python3.6/dist-packages/finetune
