### ISSUE TITLE
Error when predicting with a SequenceLabeler model loaded from file

### ISSUE THREAD

**Issue by dimidd** [IndicoDataSolutions/finetune#556]
**Describe the bug**
First train a SequenceLabeler model and serialize it to a file. **In a different session**, load the file and try to call `model.predict`. An error occurs since `predict_keys` don't include the right mode.

Traceback:

> ValueError                                Traceback (most recent call last)
> /usr/local/lib/python3.7/site-packages/finetune/base.py in _inference(self, Xs, predict_keys, n_examples, context, update_hook)
>     475                     pred[predict_keys[0]] if len(predict_keys) == 1 else pred
> --> 476                     for pred in predictions
>     477                 ]
> 
> /usr/local/lib/python3.7/site-packages/finetune/base.py in <listcomp>(.0)
>     474                 return [
> --> 475                     pred[predict_keys[0]] if len(predict_keys) == 1 else pred
>     476                     for pred in predictions
> 
> /usr/local/lib/python3.7/site-packages/tqdm/std.py in __iter__(self)
>    1103 
> -> 1104         for obj in iterable:
>    1105             yield obj
> 
> /usr/local/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py in predict(self, input_fn, predict_keys, hooks, checkpoint_path, yield_single_examples)
>     627         predictions = self._extract_keys(
> --> 628             estimator_spec.predictions, predict_keys)
>     629         all_hooks = list(input_hooks)
> 
> /usr/local/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py in _extract_keys(self, predictions, predict_keys)
>    1050       raise ValueError('Expected to run at least one output from %s, '
> -> 1051                        'provided %s.' % (existing_keys, predict_keys))
>    1052     return predictions
> 
> ValueError: Expected to run at least one output from dict_keys(['FEAT', 'SEQUENCE', 'ATTENTION']), provided ['PROBA', 'NORM'].
> 
> During handling of the above exception, another exception occurred:
> 
> FinetuneError                             Traceback (most recent call last)
> <ipython-input-14-e865d007716b> in <module>
> ----> 1 predictions = model.predict(test_texts)
> 
> /usr/local/lib/python3.7/site-packages/finetune/target_models/sequence_labeling.py in predict(self, X, per_token, context, **kwargs)
>     209         step_size = chunk_size // 3
>     210         doc_idx = -1
> --> 211         for position_seq, start_of_doc, end_of_doc, label_seq, proba_seq in self.process_long_sequence(X, context=context, **kwargs):
>     212             start, end = 0, None
>     213             if start_of_doc:
> 
> /usr/local/lib/python3.7/site-packages/finetune/base.py in process_long_sequence(self, X, context, **kwargs)
>     840 
>     841         labels, batch_probas = [], []
> --> 842         for pred in self._inference(X, predict_keys=[PredictMode.PROBAS, PredictMode.NORMAL], n_examples=len(flat_array_encoded), context=context, **kwargs):
>     843             normal_pred = pred[PredictMode.NORMAL]
>     844             if not hasattr(self, 'multi_label'):
> 
> /usr/local/lib/python3.7/site-packages/finetune/base.py in _inference(self, Xs, predict_keys, n_examples, context, update_hook)
>     478             except ValueError:
>     479                 raise FinetuneError(
> --> 480                     "Cannot call `predict()` on a model that has not been fit."
>     481                 )
>     482 
> 
> FinetuneError: Cannot call `predict()` on a model that has not been fit.

**Minimum Reproducible Example**
After running the tests in `tests/test_sequence.py`. Add the following to `tests/test_sequence.py`:

```
   def test_load_predict(self):
        """
        Ensure model returns predictions after loading from a file.
        """
        raw_docs = ["".join(text) for text in self.texts]
        texts, annotations = finetune_to_indico_sequence(raw_docs, self.texts, self.labels,
                                                         none_value=self.model.config.pad_token)
        train_texts, test_texts, train_annotations, test_annotations = train_test_split(texts, annotations, test_size=0.1)
        model = SequenceLabeler.load(self.save_file)
        predictions = self.model.predict(test_texts)
        probas = self.model.predict_proba(test_texts)
        self.assertIsInstance(probas, list)
        self.assertIsInstance(probas[0], list)
        self.assertIsInstance(probas[0][0], dict)
        self.assertIsInstance(probas[0][0]['confidence'], dict)

```
Then run `pytest tests/test_sequence.py -k 'load_predict'`.

**Expected behavior**
The loaded model should be identical to the trained one.

**Additional context**
Note that there are already tests that cover saving and loading a model in the same session. This issue only happens when loading a model in a separate session.

**Comment by benleetownsend** [comment]
In your test snippet there the model you load is not the one you call predict on. try
```
   def test_load_predict(self):
        """
        Ensure model returns predictions after loading from a file.
        """
        raw_docs = ["".join(text) for text in self.texts]
        texts, annotations = finetune_to_indico_sequence(raw_docs, self.texts, self.labels,
                                                         none_value=self.model.config.pad_token)
        train_texts, test_texts, train_annotations, test_annotations = train_test_split(texts, annotations, test_size=0.1)
        model = SequenceLabeler.load(self.save_file)
        predictions = model.predict(test_texts)
        probas = model.predict_proba(test_texts)
        self.assertIsInstance(probas, list)
        self.assertIsInstance(probas[0], list)
        self.assertIsInstance(probas[0][0], dict)
        self.assertIsInstance(probas[0][0]['confidence'], dict)
```

**Comment by benleetownsend** [comment]
I can reproduce with your snippet, but the change to call `model` as opposed to `self.model` seems to remove the problem for me. If the issue still persists can you please send over either the version if you've downloaded from pip/pypy or the commit hash if you're working directly from github.

**Comment by dimidd** [comment]
Oh right, sorry, what a stupid mistake. Please delete this issue.
