### ISSUE TITLE
Add chunk long sequences support to featurize_sequence

### ISSUE THREAD

**Issue by madisonmay** [IndicoDataSolutions/finetune#562]
Requires deciding what intended behavior is for overlapping portions of the sequence.

**Comment by benleetownsend** [comment]
Effectively merging https://github.com/IndicoDataSolutions/finetune/blob/9cbfb3d80cb9d3aec00f5e95d68a989ab4bb3d97/finetune/base.py#L502
https://github.com/IndicoDataSolutions/finetune/blob/9cbfb3d80cb9d3aec00f5e95d68a989ab4bb3d97/finetune/target_models/sequence_labeling.py#L181
