### ISSUE TITLE
McDonalds dataset link is broken

### ISSUE THREAD

**Issue by zswitten** [IndicoDataSolutions/finetune#591]
Old link was to https://www.figure-eight.com/wp-content/uploads/2016/03/McDonalds-Yelp-Sentiment-DFE.csv, which now redirects to the appen.com homepage.

The dataset is available from https://data.world/crowdflower/mcdonalds-review-sentiment/file/McDonalds-Yelp-Sentiment-DFE.csv, though it requires a login.

**Comment by madisonmay** [comment]
Hrmmm -- that's unfortunate, guess this is because of their recent acquisition by Appen. The dataset is licensed as public domain, however, so I believe we should be free to mirror this on s3 and point to a link we have control over.  Thanks so much for the bug report!
