### ISSUE TITLE
Python syntax error on line 312 of ./finetune/base.py

### ISSUE THREAD

**Issue by cclauss** [IndicoDataSolutions/finetune#65]
flake8 testing of https://github.com/IndicoDataSolutions/finetune on Python 3.7.0

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./finetune/base.py:312:21: E999 SyntaxError: invalid syntax
                    )
                    ^
1     E999 SyntaxError: invalid syntax
1
```

**Comment by benleetownsend** [comment]
Nice catch, not sure what caused this but I've got a fix in #66. Ill get tests run and merge asap.
