### ISSUE TITLE
Use on Colab Fails

### ISSUE THREAD

**Issue by Btibert3** [IndicoDataSolutions/finetune#662]
**Describe the bug**
Use on Colab fails.

**Minimum Reproducible Example**
```
! pip install finetune
from finetune.base_models import BERT, RoBERTa, GPT, GPT2, TextCNN, TCN
```

**Expected behavior**
Code above executes as expected and suggested by the `README` file

**Additional context**
I attempted to try to debug and install missing packages one-by-one, but then I eventually got a point where I started to chase installs due to tensorflow < 2.0 and hence logging this here.

**Comment by benleetownsend** [comment]
The version of Finetune that is on PyPI is quite outdated. We will try to update this soon but in the meantime I recommend using this instead
```
!pip install git+https://github.com/IndicoDataSolutions/finetune.git
```

**Comment by Btibert3** [comment]
That did the trick, thanks!
