### ISSUE TITLE
MultiLabelClassifier predictions bug

### ISSUE THREAD

**Issue by JonathanBt** [IndicoDataSolutions/finetune#684]
Hi, I'm using RoBERTa to train a multi-label classifier with 17 binary labels using the following code:
```
from finetune import *
from finetune.base_models import RoBERTa
model = MultiLabelClassifier(base_model=RoBERTa, low_memory_mode=True, chunk_long_sequences=False)
```
This works fine but when I want to predict using
```
model.predict(X_test)
```
it simply returns [0,1] for each example instead of the 17 binary labels:
```
[[0, 1],
 [0, 1],
 [0, 1],
 [0, 1],
 [0, 1],
 [0, 1],
 ...
```
Could you please have a look into this? Thank you!

**Comment by JonathanBt** [comment]
I found the error, I was using one-hot-encoded labels instead of a list of the labels themselves.

**Comment by madisonmay** [comment]
Glad you were able to get things sorted! We definitely could + should have caught this with input validation so appreciate you opening the issue.
