### ISSUE TITLE
Comparison.predict_proba doesn't returns probability distribution

### ISSUE THREAD

**Issue by rmotsar** [IndicoDataSolutions/finetune#85]
**Describe the bug**
Method `Comparison.predict_proba` returns most likely class, but not probabilities of classes 

**Minimum Reproducible Example**
A short code snippet which reproduces the exception

`
from finetune import Comparison
model = Comparison.load(model_path)
model.predict_proba("my sentence", "other sentence")
`

**Expected behavior**
`{0: float, 1: float}`

**Additional context**
`[int]`

**Comment by madisonmay** [comment]
Thanks for the bug report @rmotsar !  We just noticed this issue as well -- should be resolved by EOD.  We'll ping you when the fix is merged in + regression tested.

**Comment by madisonmay** [comment]
@rmotsar should be resolved now.  Thanks again for the report.
